mutation {
  createUser(
    args: {
      name: "test"
      uid: "t_e_s_t"
      email: "test@example.com"
      password: "hogehoge"
      published: false
    }
  ) {
    user {
      id
      uid
      name
      email
      password
      published
      createdAt
      updatedAt
    }
  }
}
mutation {
  deleteUser(args: { uid: "t_e_s_t" }) {
    id
    uid
    name
    email
    password
    published
    createdAt
    updatedAt
  }
}
